---
title: "ExtraCredit"
author: "Alberto Melendez"
date: "February 14, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r}
library(tmap)
library(dplyr)
library(tidyverse)
library(sf)

ODDATA <- read.csv("od2015_Tacoma.csv")
WACT <- read.csv("wac2015_Tacoma.csv")
WACB <- read.csv("wac2015_Tacoma_Block.csv")
tacomablockshp <- st_read("tacomablocks-polygon.shp")
tacomatractshp <- st_read("tacoma_tract2.shp")
Washingtontractshp <- st_read("cb_2017_53_tract_500k.shp")

WACB$GEOID10 <-  WACB$w_geocode

WACBLOCK <- merge(tacomablockshp, WACB, by=c("GEOID10"))

WACT$GEOID10 <- WACT$wt
WACTRACT <- merge(tacomatractshp, WACT, by=c("GEOID10"))

#WACB$wt <-  substr(WACB$GEOID10, 1, nchar(WACB$wt)-4)
#WACT$wt <-  substr(WACT$GEOID10, 1, nchar(WACT$wt)-4)

#WACT_WACB <- c(WACT, WACB)

#tacoma_tract <- merge(tacomatractshp, WACT_WACB, by=("wt"))

```

```{r Manufacturing Jobs}
WACTRACT$Manufacturing <- WACTRACT$CNS05

tm_shape(WACTRACT) + tm_fill(col = "Manufacturing") + tm_borders()

```

```{r}

WACTRACT$Transportation <- WACTRACT$CNS06

tm_shape(WACTRACT) + tm_fill(col = "Transportation") + tm_borders()
```

```{r}

WACTRACT$Healthcare <- WACTRACT$CNS16

tm_shape(WACTRACT) + tm_fill(col = "Healthcare") + tm_borders()
```