---
title: "Part 3 Visualizing and Mapping"
author: "Emmanuel Robi "
date: "GEOG 458"
output: html_document
---
  
```{r Packages, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(dplyr)
library(tmap)
library(leaflet)
library(ggplot2)
library(shiny)
```

#Data 
```{r PART3.3, include = TRUE}
ODDATA <- read.csv("od2015_Tacoma.csv")
block_data <- read.csv("tacoma_blocks2.csv")
track_data <- read.csv("tacoma_tracts2.csv")
WACT <- read.csv("wac2015_Tacoma.csv")
WACB <- read.csv("wac2015_Tacoma_Block.csv")
tacomablockshp <- st_read("tacomablocks-polygon.shp")
tacomatrackshp <- st_read("pie10ct.shp")
Washingtontrackshp <- st_read("cb_2017_53_tract_500k.shp")
```

#Part 3.2 
```{r PART3.3, include = TRUE}
library(tidyverse)
baseData=read.csv("wa_od_main_JT01_2015.csv")
odData=baseData
#Filter out Tacoma Codes and pretty up the geocodes
odData <- filter(odData, w_geocode > 530530603000000 & w_geocode < 530530620999999 | h_geocode > 530530603000000 & h_geocode < 530530620999999)
odData$w_geocode<-as.character(odData$w_geocode)
odData$h_geocode<-as.character(odData$h_geocode)
odData$w_geocode[which(length(odData$w_geocode) == 14)]<-paste0("0",odData$w_geocode[which(length(odData$w_geocode) == 14)])
odData$h_geocode[which(length(odData$h_geocode) == 14)]<-paste0("0",odData$h_geocode[which(length(odData$h_geocode) == 14)])
#Making Columns for worktract and hometract
odData$wt<-substr(odData$w_geocode,1,11)
odData$ht<-substr(odData$h_geocode,1,11)
odData
#Plots compare Total Numbers of Jobs to Number of jobs in Goods Producing industry sectors and Number of jobs in Trade, Transportation, and Utilities industry sectors
p <-ggplot(data = odData, aes(odData$S000, odData$SI01))
p + geom_bar(stat="identity", aes(fill = odData$SI02)) + xlab("Total Number of Jobs") + ylab("Number of jobs in Goods Producing industry sectors") + labs(fill = "Number of jobs in Trade, Transportation, and Utilities industry sectors")
```



#Part 3.3
```{r PART3.3, include = TRUE}
library(dplyr)

###Create Map 1
# Block Shapefile with WAC 
WACB$GEOID10= WACB$w_geocode


WACBLOCK <- merge(tacomablockshp, WACB, by=c("GEOID10"))

#Change label name for plot Block 
WACBLOCK$Population = WACBLOCK$CE01


#plot block
BLOCK_MAP <- tm_shape(WACBLOCK) +tm_polygons() +tm_symbols(col="Population") + tm_borders() +tm_layout(title = "Number of jobs with earnings $1250/month or less in the City of Tacoma on a Block Level", title.position = c("RIGHT", "TOP")) 

BLOCK_MAP

##Create Map 2
#Number of jobs with earnings $1250/month or less 
#plot 2 track
WACTRACK <- merge(tacomatrackshp, WACT, by=c("GEOID10"))
WACTRACK$Population = WACTRACK$CE01

TRACK_MAP <- tm_shape(WACTRACK) +tm_polygons() +tm_symbols(col="Population") + tm_borders() +tm_layout(title = "Number of jobs with earnings $1250/month or less in the City of Tacoma on a Tract Level", title.position = c("RIGHT", "TOP"))

TRACK_MAP
```


#Part 3.4
```{r PART3.3, include = TRUE}
###Create Map of OD 
HomeTrack1 <-filter(ODDATA, ht == 53053060905)

Washingtontrackshp$wt = Washingtontrackshp$GEOID

HomeTrack1Merge <- merge(Washingtontrackshp, HomeTrack1, by=c("wt"), all = TRUE)
HomeTrack1Merge[is.na(HomeTrack1Merge)] <- 0 

 tm_shape(HomeTrack1Merge) +tm_polygons() +  tm_symbols(col="wt") + tm_borders() +tm_layout(title = "Points of places where people who live in area 53053060905 work", title.position = c("RIGHT", "TOP")) 

```



